/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObservationsRouteImport } from './routes/observations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeciesIndexRouteImport } from './routes/species.index'
import { Route as SpeciesSpeciesIdRouteImport } from './routes/species.$speciesId'
import { ServerRoute as ApiSpeciesServerRouteImport } from './routes/api/species'

const rootServerRouteImport = createServerRootRoute()

const ObservationsRoute = ObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesSpeciesIdRoute = SpeciesSpeciesIdRouteImport.update({
  id: '/species/$speciesId',
  path: '/species/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeciesServerRoute = ApiSpeciesServerRouteImport.update({
  id: '/api/species',
  path: '/api/species',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/observations': typeof ObservationsRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species': typeof SpeciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/observations': typeof ObservationsRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species': typeof SpeciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/observations': typeof ObservationsRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/observations' | '/species/$speciesId' | '/species'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/observations' | '/species/$speciesId' | '/species'
  id: '__root__' | '/' | '/observations' | '/species/$speciesId' | '/species/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObservationsRoute: typeof ObservationsRoute
  SpeciesSpeciesIdRoute: typeof SpeciesSpeciesIdRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/species': typeof ApiSpeciesServerRoute
}
export interface FileServerRoutesByTo {
  '/api/species': typeof ApiSpeciesServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/species': typeof ApiSpeciesServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/species'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/species'
  id: '__root__' | '/api/species'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSpeciesServerRoute: typeof ApiSpeciesServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/observations': {
      id: '/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof ObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$speciesId': {
      id: '/species/$speciesId'
      path: '/species/$speciesId'
      fullPath: '/species/$speciesId'
      preLoaderRoute: typeof SpeciesSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/species': {
      id: '/api/species'
      path: '/api/species'
      fullPath: '/api/species'
      preLoaderRoute: typeof ApiSpeciesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObservationsRoute: ObservationsRoute,
  SpeciesSpeciesIdRoute: SpeciesSpeciesIdRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSpeciesServerRoute: ApiSpeciesServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
