/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ObservationsRouteImport } from './routes/observations'
import { Route as GazetteerRouteImport } from './routes/gazetteer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeciesIndexRouteImport } from './routes/species.index'
import { Route as SpeciesSpeciesIdRouteImport } from './routes/species.$speciesId'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiSpeciesRouteImport } from './routes/api/species'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationsRoute = ObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteerRoute = GazetteerRouteImport.update({
  id: '/gazetteer',
  path: '/gazetteer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesSpeciesIdRoute = SpeciesSpeciesIdRouteImport.update({
  id: '/species/$speciesId',
  path: '/species/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeciesRoute = ApiSpeciesRouteImport.update({
  id: '/api/species',
  path: '/api/species',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gazetteer': typeof GazetteerRoute
  '/observations': typeof ObservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weather': typeof WeatherRoute
  '/api/species': typeof ApiSpeciesRoute
  '/api/weather': typeof ApiWeatherRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gazetteer': typeof GazetteerRoute
  '/observations': typeof ObservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weather': typeof WeatherRoute
  '/api/species': typeof ApiSpeciesRoute
  '/api/weather': typeof ApiWeatherRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species': typeof SpeciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gazetteer': typeof GazetteerRoute
  '/observations': typeof ObservationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weather': typeof WeatherRoute
  '/api/species': typeof ApiSpeciesRoute
  '/api/weather': typeof ApiWeatherRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gazetteer'
    | '/observations'
    | '/sitemap.xml'
    | '/weather'
    | '/api/species'
    | '/api/weather'
    | '/species/$speciesId'
    | '/species/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gazetteer'
    | '/observations'
    | '/sitemap.xml'
    | '/weather'
    | '/api/species'
    | '/api/weather'
    | '/species/$speciesId'
    | '/species'
  id:
    | '__root__'
    | '/'
    | '/gazetteer'
    | '/observations'
    | '/sitemap.xml'
    | '/weather'
    | '/api/species'
    | '/api/weather'
    | '/species/$speciesId'
    | '/species/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GazetteerRoute: typeof GazetteerRoute
  ObservationsRoute: typeof ObservationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeatherRoute: typeof WeatherRoute
  ApiSpeciesRoute: typeof ApiSpeciesRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  SpeciesSpeciesIdRoute: typeof SpeciesSpeciesIdRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observations': {
      id: '/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof ObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazetteer': {
      id: '/gazetteer'
      path: '/gazetteer'
      fullPath: '/gazetteer'
      preLoaderRoute: typeof GazetteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/species'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$speciesId': {
      id: '/species/$speciesId'
      path: '/species/$speciesId'
      fullPath: '/species/$speciesId'
      preLoaderRoute: typeof SpeciesSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/species': {
      id: '/api/species'
      path: '/api/species'
      fullPath: '/api/species'
      preLoaderRoute: typeof ApiSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GazetteerRoute: GazetteerRoute,
  ObservationsRoute: ObservationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeatherRoute: WeatherRoute,
  ApiSpeciesRoute: ApiSpeciesRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  SpeciesSpeciesIdRoute: SpeciesSpeciesIdRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
